name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  macos-test:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test
